Add Shortcuts
paradoxuum/commander pull request #32
Opened 2024-06-09 21:13 UTC by longuint

I added the option to use shortcuts on each command using Keycode objects. I've also updated the docs to reflect the changes I've made.

2024-06-09 21:16 UTC, longuint commented on src/client/interface/components/shortcut.tsx
Couldn't find an efficient way to get access to the `ClientDispatcher` so this file is being stored in the interface.

2024-06-09 21:21 UTC, longuint commented on src/client/interface/components/shortcut.tsx
> +	shortcuts.forEach((shortcut, index) => {
Refactoring this code might make it more understandable.

2024-06-09 21:22 UTC, longuint commented on src/client/interface/components/shortcut.tsx
> +	registry.commandRegistered.Connect((command) => {
I need to write tests to make sure this works.

2024-06-10 03:33 UTC, longuint commented
I took a crack at adding a shortcuts panel in the suggestions menu, couldn't quite figure it out. maybe someone could try it out. I was thinking a list of all shortcuts relating to a command, with modifier keys shown with the highlight colors.

2024-06-10 12:16 UTC, paradoxuum commented
Haven't got the time to review this yet, but would you be able to set the formatter back to Biome? Seems to be set to Prettier so it looks like there's more changes than there actually are.

You should be able to revert the change to the formatter for `[typescriptreact]` in `.vscode/settings.json` then run `pnpm biome check --write --unsafe` to apply formatting/linting changes to the project. In terms of actually using Biome as a formatter in vscode, you can install the [extension](https://marketplace.visualstudio.com/items?itemName=biomejs.biome).

2024-06-11 11:17 UTC, paradoxuum requested changes
Overall LGTM, just some minor changes.

Going forward, the approach I'd like to take with this would be abstracting the shortcuts functionality outside of the interface and using something like `ContextActionService.BindAction` to handle bindings. This is a good starting point, however.

2024-06-11 11:17 UTC, paradoxuum commented on src/shared/core/decorators.ts
> +	Shortcut = "shortcut",
`MetadataKey` is only used for decorators, so this should be removed.
```suggestion
```

2024-06-11 16:14 UTC, longuint commented
Making some changes based off of your suggestions, changes will be pushed soon.

2024-06-11 18:08 UTC, longuint commented
> Overall LGTM, just some minor changes.
> 
> Going forward, the approach I'd like to take with this would be abstracting the shortcuts functionality outside of the interface and using something like `ContextActionService.BindAction` to handle bindings. This is a good starting point, however.

The support for `ContextActionService` will continue to be refactored to be more powerful but for now you can bind commands to these actions.

2024-06-11 21:03 UTC, longuint reviewed
Implemented suggestions.

2024-06-12 15:55 UTC, paradoxuum commented
Looks good, thanks for the PR!

2024-06-12 15:56 UTC, merged